# Generated by Django 3.2 on 2021-04-21 12:03

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='game_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('timer', models.IntegerField(default=0, verbose_name='Таймер в минутах')),
                ('rating', models.IntegerField(default=0, verbose_name='+рейтинг')),
                ('balance', models.IntegerField(default=0, verbose_name='+баланс в %')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=api.models.game_images_dir)),
                ('code', models.CharField(default=uuid.uuid4, max_length=36)),
                ('lev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.level')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to='games/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('result', models.BooleanField(default=False)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.level')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
