# Generated by Django 3.2 on 2021-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to='ad/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='video',
            field=models.FileField(blank=True, upload_to='ad/'),
        ),
    ]
