# Generated by Django 3.2 on 2021-04-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_feedback_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='levels/', verbose_name='Задний фон'),
        ),
    ]
