# Generated by Django 3.2 on 2021-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210308_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Guest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_allow_email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_vip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='size',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, default=0, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatar', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=1000, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_image',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, null=True, verbose_name='Ник'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='study',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
