# Generated by Django 3.2 on 2021-04-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210424_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_balance',
            field=models.IntegerField(default=0, verbose_name='Баланс снимаемый'),
        ),
    ]
