# Generated by Django 3.2 on 2021-04-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_add_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wechatid',
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.TextField(blank=True, null=True, verbose_name='Профессия'),
        ),
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.TextField(blank=True, null=True, verbose_name='Работа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='study',
            field=models.TextField(blank=True, null=True, verbose_name='Образование'),
        ),
    ]
