# Generated by Django 3.2 on 2021-05-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='games_count',
            field=models.IntegerField(default=0),
        ),
    ]
