# Generated by Django 3.2 on 2021-05-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_games_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_add',
            field=models.IntegerField(default=0, verbose_name='Баланс пополнен всего'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_remove',
            field=models.IntegerField(default=0, verbose_name='Баланс снят всего'),
        ),
    ]
