# Generated by Django 3.2 on 2022-02-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210520_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='add_balance',
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Баланс'),
        ),
    ]
