# Generated by Django 3.2 on 2022-04-01 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20220203_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='user',
            name='study',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Адрес кошелька'),
        ),
    ]
